<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AbstractWebDriverEventListener</name>
   <tag></tag>
   <elementGuidId>2aeeea3c-dabc-4a93-b26d-6da99fbeb299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;class in org.openqa.selenium.support.events&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'AbstractWebDriverEventListener')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32dee601-7bce-4463-990a-8df3ad1d37e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>org/openqa/selenium/support/events/AbstractWebDriverEventListener.html</value>
      <webElementGuid>fac2500d-8091-4fe4-8eed-231795b1e5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.support.events</value>
      <webElementGuid>e7fd781f-69f4-4148-b736-5e532e120e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>62340e92-d091-4888-891e-9754c86aa9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AbstractWebDriverEventListener</value>
      <webElementGuid>235e3acb-3b36-45ad-bb73-f0c521a691f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[@class=&quot;indexContainer&quot;]/ul[1]/li[7]/a[1]</value>
      <webElementGuid>e4e6d293-a386-48a0-a350-7c5934f206b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Overview/iframe_packageFrame</value>
      <webElementGuid>06fa3d04-dd48-42e5-bdc6-10ad1ba40e3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AbstractWebDriverEventListener')]</value>
      <webElementGuid>7d9d10c8-aa13-42d4-bd1c-a025011eab3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbstractHttpResponseCodec'])[1]/following::a[1]</value>
      <webElementGuid>2dcc1392-9742-4e1b-b7bb-7bf8e0845fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbstractHttpCommandCodec.CommandSpec'])[1]/following::a[2]</value>
      <webElementGuid>f550c75a-da4c-4758-a9a5-ebd925224402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AcceptedW3CCapabilityKeys'])[1]/preceding::a[1]</value>
      <webElementGuid>dae30e02-e356-49dc-8f61-afaf31dcb26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/preceding::a[2]</value>
      <webElementGuid>417a98d4-83c3-4591-8581-5b3589021a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AbstractWebDriverEventListener']/parent::*</value>
      <webElementGuid>bf697eab-f406-4209-83df-cd2c7c6ab9ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'org/openqa/selenium/support/events/AbstractWebDriverEventListener.html')]</value>
      <webElementGuid>659418e8-c8e4-4c75-8cae-3b3c1ce2a396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>6a265ff3-9bab-44db-9194-2b094f42c044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'org/openqa/selenium/support/events/AbstractWebDriverEventListener.html' and @title = 'class in org.openqa.selenium.support.events' and (text() = 'AbstractWebDriverEventListener' or . = 'AbstractWebDriverEventListener')]</value>
      <webElementGuid>812d13a3-4889-4a2d-8b4a-7b99aa1cf6a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
